name: Feature Request
description: Share an idea for a feature or describe an example that would improve the documentation
labels: [ "cX", "feature" ]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the idea
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Example
      description: |
        A simple example of the new feature in action (include PHP code, Twig variable, YAML config, etc.)
        If the new feature changes an existing feature, include a simple before/after comparison.
